OPENAI_API_KEY="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"
HUGGINGFACEHUB_API_TOKEN=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
openai_api_key="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"